/**************************************/
/* Description : NVIC interface File  */
/* Author      : hossam               */
/* Version     : 0.1V                 */
/* Date        : 23:50:49  29 Jul 2023*/
/* History     : 0.1V Initial Creation*/
/**************************************/




#ifndef NVIC_INTERFACE_H
#define NVIC_INTERFACE_H
typedef enum{
	NVIC__STATE___DISABLE,
	NVIC__STATE___ENABLE
}NVIC_State_et;
typedef enum __attribute__((__packed__)){

	NVIC__INTERRUPT_SIGNAL___WWDG,
	NVIC__INTERRUPT_SIGNAL___EXTI16_OR_PVD,
	NVIC__INTERRUPT_SIGNAL___EXTI21_OR_TAMP_STAMP,
	NVIC__INTERRUPT_SIGNAL___EXTI22_OR_RTC_WKUP,
	NVIC__INTERRUPT_SIGNAL___FLASH,
	NVIC__INTERRUPT_SIGNAL___RCC,
	NVIC__INTERRUPT_SIGNAL___EXTI0,
	NVIC__INTERRUPT_SIGNAL___EXTI1,
	NVIC__INTERRUPT_SIGNAL___EXTI2,
	NVIC__INTERRUPT_SIGNAL___EXTI3,
	NVIC__INTERRUPT_SIGNAL___EXTI4,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream0,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream1,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream2,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream3,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream4,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream5,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream6,
	NVIC__INTERRUPT_SIGNAL___ADC,
	NVIC__INTERRUPT_SIGNAL___EXTI9_5,
	NVIC__INTERRUPT_SIGNAL___TIM1_BRK_TIM9,
	NVIC__INTERRUPT_SIGNAL___TIM1_UP_TIM10,
	NVIC__INTERRUPT_SIGNAL___TIM1_TRG_COM_TIM11,
	NVIC__INTERRUPT_SIGNAL___TIM1_CC,
	NVIC__INTERRUPT_SIGNAL___TIM2,
	NVIC__INTERRUPT_SIGNAL___TIM3,
	NVIC__INTERRUPT_SIGNAL___TIM4,
	NVIC__INTERRUPT_SIGNAL___I2C1_EV,
	NVIC__INTERRUPT_SIGNAL___I2C1_ER,
	NVIC__INTERRUPT_SIGNAL___I2C2_EV,
	NVIC__INTERRUPT_SIGNAL___I2C2_ER,
	NVIC__INTERRUPT_SIGNAL___SPI1,
	NVIC__INTERRUPT_SIGNAL___SPI2,
	NVIC__INTERRUPT_SIGNAL___USART1,
	NVIC__INTERRUPT_SIGNAL___USART2,
	NVIC__INTERRUPT_SIGNAL___EXTI15_10,
	NVIC__INTERRUPT_SIGNAL___EXTI17_OR_RTC_Alarm,
	NVIC__INTERRUPT_SIGNAL___EXTI18_OR_OTG_FS_WKUP,
	NVIC__INTERRUPT_SIGNAL___DMA1_Stream7,
	NVIC__INTERRUPT_SIGNAL___SDIO,
	NVIC__INTERRUPT_SIGNAL___TIM5,
	NVIC__INTERRUPT_SIGNAL___SPI3,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream0,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream1,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream2,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream3,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream4,
	NVIC__INTERRUPT_SIGNAL___OTG_FS,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream5,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream6,
	NVIC__INTERRUPT_SIGNAL___DMA2_Stream7,
	NVIC__INTERRUPT_SIGNAL___USART6,
	NVIC__INTERRUPT_SIGNAL___I2C3_EV,
	NVIC__INTERRUPT_SIGNAL___I2C3_ER,
	NVIC__INTERRUPT_SIGNAL___FPU,
	NVIC__INTERRUPT_SIGNAL___SPI4,
}InterruptSignal_et;
typedef enum  __attribute__((__packed__)){
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_1_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_2_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_3_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_4_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_5_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_6_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_7_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_8_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_9_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_10_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_11_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_12_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_13_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_14_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_15_SUBGROUP_1,
	NVIC__PRIORITY_16_GROUP_1_SUBGROUPS___GROUP_16_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_1_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_1_SUBGROUP_2,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_2_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_2_SUBGROUP_2,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_3_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_3_SUBGROUP_2,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_4_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_4_SUBGROUP_2,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_5_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_5_SUBGROUP_2,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_6_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_6_SUBGROUP_2,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_7_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_7_SUBGROUP_2,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_8_SUBGROUP_1,
	NVIC__PRIORITY_8_GROUP_2_SUBGROUPS___GROUP_8_SUBGROUP_2,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_1_SUBGROUP_1,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_1_SUBGROUP_2,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_1_SUBGROUP_3,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_1_SUBGROUP_4,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_2_SUBGROUP_1,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_2_SUBGROUP_2,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_2_SUBGROUP_3,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_2_SUBGROUP_4,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_3_SUBGROUP_1,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_3_SUBGROUP_2,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_3_SUBGROUP_3,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_3_SUBGROUP_4,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_4_SUBGROUP_1,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_4_SUBGROUP_2,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_4_SUBGROUP_3,
	NVIC__PRIORITY_4_GROUP_4_SUBGROUPS___GROUP_4_SUBGROUP_4,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_1,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_2,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_3,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_4,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_5,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_6,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_7,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_1_SUBGROUP_8,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_1,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_2,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_3,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_4,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_5,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_6,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_7,
	NVIC__PRIORITY_2_GROUP_8_SUBGROUPS___GROUP_2_SUBGROUP_8,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_1,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_2,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_3,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_4,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_5,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_6,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_7,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_8,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_9,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_10,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_11,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_12,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_13,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_14,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_15,
	NVIC__PRIORITY_1_GROUP_16_SUBGROUPS___GROUP_1_SUBGROUP_16,
}PriorityGroupAndSubgroup_et;
typedef enum  __attribute__((__packed__)){
	NVIC__PRIORITY_GROUPING_STYLE___16_GROUP_1_SUBGROUPS,
	NVIC__PRIORITY_GROUPING_STYLE___8_GROUP_2_SUBGROUPS=4,
	NVIC__PRIORITY_GROUPING_STYLE___4_GROUP_4_SUBGROUPS,
	NVIC__PRIORITY_GROUPING_STYLE___2_GROUP_8_SUBGROUPS,
	NVIC__PRIORITY_GROUPING_STYLE___1_GROUP_16_SUBGROUPS,
}PriorityGroupingStyle_et;
typedef enum  __attribute__((__packed__)){
	NVIC__INTERRUPT_SET_MODE___NOT_PENDING,
	NVIC__INTERRUPT_SET_MODE___PENDING,
	NVIC__INTERRUPT_SET_MODE___ACTIVE,
	NVIC__INTERRUPT_SET_MODE___ACTIVE_AND_PENDING,

}InterruptSetMode_et;
typedef enum  __attribute__((__packed__)){
	NVIC__INTERRUPT_READ_MODE___NOT_ACTIVE_EITHER_PENDING,
	NVIC__INTERRUPT_READ_MODE___PENDING,
	NVIC__INTERRUPT_READ_MODE___ACTIVE,
	NVIC__INTERRUPT_READ_MODE___ACTIVE_AND_PENDING,

}InterruptReadMode_et;
class NVIC_ct{
	public:
	 NVIC_ct(void);

void NVIC_vSetInterruptState(InterruptSignal_et InterruptSignal_e,NVIC_State_et NVIC_State_e);
NVIC_State_et NVIC_enuReadInterruptState(InterruptSignal_et InterruptSignal_e);

void NVIC_vSetInterruptMode(InterruptSignal_et InterruptSignal_e,InterruptSetMode_et InterruptSetMode_e);
InterruptReadMode_et NVIC_enuReadInterruptMode(InterruptSignal_et InterruptSignal_e);

ErrorStatus_et NVIC_enuSetInterruptPriority(InterruptSignal_et InterruptSignal_e,PriorityGroupAndSubgroup_et PriorityGroupAndSubgroup_e);
PriorityGroupAndSubgroup_et NVIC_enuReadInterruptPriority(InterruptSignal_et InterruptSignal_e);

};





#endif
