/**************************************/
/* Description : GPIO program File    */
/* Author      : hossam               */
/* Version     : 0.1V                 */
/* Date        : 03:13:44  11 Jul 2023*/
/* History     : 0.1V Initial Creation*/
/**************************************/

#include "../../../LIB/STD_TYPES/STD_TYPES.h"
#include "../../../LIB/STD_MACROS/STD_MACROS.h"

#include "GPIO_interface.h"
#include "GPIO_config.h"
#include "GPIO_private.h"



/*PRE-BUILD CONFIGURATION(PRE-PROCESSING)*/
GPIO_ct::GPIO_ct(void)
{
GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___MODER)=PIN_A0_MODE|PIN_A1_MODE<<2|PIN_A2_MODE<<4|PIN_A3_MODE<<6|
					   PIN_A4_MODE<<8|PIN_A5_MODE<<10|PIN_A6_MODE<<12|PIN_A7_MODE<<14|
					   PIN_A8_MODE<<16|PIN_A9_MODE<<18|PIN_A10_MODE<<20|PIN_A11_MODE<<22|
					   PIN_A12_MODE<<24|PIN_A13_MODE<<26|PIN_A14_MODE<<28|PIN_A15_MODE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___MODER)=PIN_B0_MODE|PIN_B1_MODE<<2|PIN_B2_MODE<<4|PIN_B3_MODE<<6|
					   PIN_B4_MODE<<8|PIN_B5_MODE<<10|PIN_B6_MODE<<12|PIN_B7_MODE<<14|
					   PIN_B8_MODE<<16|PIN_B9_MODE<<18|PIN_B10_MODE<<20|PIN_B11_MODE<<22|
					   PIN_B12_MODE<<24|PIN_B13_MODE<<26|PIN_B14_MODE<<28|PIN_B15_MODE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___MODER)=PIN_C0_MODE|PIN_C1_MODE<<2|PIN_C2_MODE<<4|PIN_C3_MODE<<6|
					   PIN_C4_MODE<<8|PIN_C5_MODE<<10|PIN_C6_MODE<<12|PIN_C7_MODE<<14|
					   PIN_C8_MODE<<16|PIN_C9_MODE<<18|PIN_C10_MODE<<20|PIN_C11_MODE<<22|
					   PIN_C12_MODE<<24|PIN_C13_MODE<<26|PIN_C14_MODE<<28|PIN_C15_MODE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___MODER)=PIN_D0_MODE|PIN_D1_MODE<<2|PIN_D2_MODE<<4|PIN_D3_MODE<<6|
					   PIN_D4_MODE<<8|PIN_D5_MODE<<10|PIN_D6_MODE<<12|PIN_D7_MODE<<14|
					   PIN_D8_MODE<<16|PIN_D9_MODE<<18|PIN_D10_MODE<<20|PIN_D11_MODE<<22|
					   PIN_D12_MODE<<24|PIN_D13_MODE<<26|PIN_D14_MODE<<28|PIN_D15_MODE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___MODER)=PIN_E0_MODE|PIN_E1_MODE<<2|PIN_E2_MODE<<4|PIN_E3_MODE<<6|
					   PIN_E4_MODE<<8|PIN_E5_MODE<<10|PIN_E6_MODE<<12|PIN_E7_MODE<<14|
					   PIN_E8_MODE<<16|PIN_E9_MODE<<18|PIN_E10_MODE<<20|PIN_E11_MODE<<22|
					   PIN_E12_MODE<<24|PIN_E13_MODE<<26|PIN_E14_MODE<<28|PIN_E15_MODE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___MODER)=PIN_H0_MODE|PIN_H1_MODE<<2|PIN_H2_MODE<<4|PIN_H3_MODE<<6|
					   PIN_H4_MODE<<8|PIN_H5_MODE<<10|PIN_H6_MODE<<12|PIN_H7_MODE<<14|
					   PIN_H8_MODE<<16|PIN_H9_MODE<<18|PIN_H10_MODE<<20|PIN_H11_MODE<<22|
					   PIN_H12_MODE<<24|PIN_H13_MODE<<26|PIN_H14_MODE<<28|PIN_H15_MODE<<30;

GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___PUPDR)=PIN_A0_ATTACHMENT_TYPE|PIN_A1_ATTACHMENT_TYPE<<2|PIN_A2_ATTACHMENT_TYPE<<4|PIN_A3_ATTACHMENT_TYPE<<6|
					   PIN_A4_ATTACHMENT_TYPE<<8|PIN_A5_ATTACHMENT_TYPE<<10|PIN_A6_ATTACHMENT_TYPE<<12|PIN_A7_ATTACHMENT_TYPE<<14|
					   PIN_A8_ATTACHMENT_TYPE<<16|PIN_A9_ATTACHMENT_TYPE<<18|PIN_A10_ATTACHMENT_TYPE<<20|PIN_A11_ATTACHMENT_TYPE<<22|
					   PIN_A12_ATTACHMENT_TYPE<<24|PIN_A13_ATTACHMENT_TYPE<<26|PIN_A14_ATTACHMENT_TYPE<<28|PIN_A15_ATTACHMENT_TYPE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___PUPDR)=PIN_B0_ATTACHMENT_TYPE|PIN_B1_ATTACHMENT_TYPE<<2|PIN_B2_ATTACHMENT_TYPE<<4|PIN_B3_ATTACHMENT_TYPE<<6|
					   PIN_B4_ATTACHMENT_TYPE<<8|PIN_B5_ATTACHMENT_TYPE<<10|PIN_B6_ATTACHMENT_TYPE<<12|PIN_B7_ATTACHMENT_TYPE<<14|
					   PIN_B8_ATTACHMENT_TYPE<<16|PIN_B9_ATTACHMENT_TYPE<<18|PIN_B10_ATTACHMENT_TYPE<<20|PIN_B11_ATTACHMENT_TYPE<<22|
					   PIN_B12_ATTACHMENT_TYPE<<24|PIN_B13_ATTACHMENT_TYPE<<26|PIN_B14_ATTACHMENT_TYPE<<28|PIN_B15_ATTACHMENT_TYPE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___PUPDR)=PIN_C0_ATTACHMENT_TYPE|PIN_C1_ATTACHMENT_TYPE<<2|PIN_C2_ATTACHMENT_TYPE<<4|PIN_C3_ATTACHMENT_TYPE<<6|
					   PIN_C4_ATTACHMENT_TYPE<<8|PIN_C5_ATTACHMENT_TYPE<<10|PIN_C6_ATTACHMENT_TYPE<<12|PIN_C7_ATTACHMENT_TYPE<<14|
					   PIN_C8_ATTACHMENT_TYPE<<16|PIN_C9_ATTACHMENT_TYPE<<18|PIN_C10_ATTACHMENT_TYPE<<20|PIN_C11_ATTACHMENT_TYPE<<22|
					   PIN_C12_ATTACHMENT_TYPE<<24|PIN_C13_ATTACHMENT_TYPE<<26|PIN_C14_ATTACHMENT_TYPE<<28|PIN_C15_ATTACHMENT_TYPE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___PUPDR)=PIN_D0_ATTACHMENT_TYPE|PIN_D1_ATTACHMENT_TYPE<<2|PIN_D2_ATTACHMENT_TYPE<<4|PIN_D3_ATTACHMENT_TYPE<<6|
					   PIN_D4_ATTACHMENT_TYPE<<8|PIN_D5_ATTACHMENT_TYPE<<10|PIN_D6_ATTACHMENT_TYPE<<12|PIN_D7_ATTACHMENT_TYPE<<14|
					   PIN_D8_ATTACHMENT_TYPE<<16|PIN_D9_ATTACHMENT_TYPE<<18|PIN_D10_ATTACHMENT_TYPE<<20|PIN_D11_ATTACHMENT_TYPE<<22|
					   PIN_D12_ATTACHMENT_TYPE<<24|PIN_D13_ATTACHMENT_TYPE<<26|PIN_D14_ATTACHMENT_TYPE<<28|PIN_D15_ATTACHMENT_TYPE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___PUPDR)=PIN_E0_ATTACHMENT_TYPE|PIN_E1_ATTACHMENT_TYPE<<2|PIN_E2_ATTACHMENT_TYPE<<4|PIN_E3_ATTACHMENT_TYPE<<6|
					   PIN_E4_ATTACHMENT_TYPE<<8|PIN_E5_ATTACHMENT_TYPE<<10|PIN_E6_ATTACHMENT_TYPE<<12|PIN_E7_ATTACHMENT_TYPE<<14|
					   PIN_E8_ATTACHMENT_TYPE<<16|PIN_E9_ATTACHMENT_TYPE<<18|PIN_E10_ATTACHMENT_TYPE<<20|PIN_E11_ATTACHMENT_TYPE<<22|
					   PIN_E12_ATTACHMENT_TYPE<<24|PIN_E13_ATTACHMENT_TYPE<<26|PIN_E14_ATTACHMENT_TYPE<<28|PIN_E15_ATTACHMENT_TYPE<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___PUPDR)=PIN_H0_ATTACHMENT_TYPE|PIN_H1_ATTACHMENT_TYPE<<2|PIN_H2_ATTACHMENT_TYPE<<4|PIN_H3_ATTACHMENT_TYPE<<6|
					   PIN_H4_ATTACHMENT_TYPE<<8|PIN_H5_ATTACHMENT_TYPE<<10|PIN_H6_ATTACHMENT_TYPE<<12|PIN_H7_ATTACHMENT_TYPE<<14|
					   PIN_H8_ATTACHMENT_TYPE<<16|PIN_H9_ATTACHMENT_TYPE<<18|PIN_H10_ATTACHMENT_TYPE<<20|PIN_H11_ATTACHMENT_TYPE<<22|
					   PIN_H12_ATTACHMENT_TYPE<<24|PIN_H13_ATTACHMENT_TYPE<<26|PIN_H14_ATTACHMENT_TYPE<<28|PIN_H15_ATTACHMENT_TYPE<<30;

GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___OSPEEDR)=PIN_A0_OUTPUT_SPEED|PIN_A1_OUTPUT_SPEED<<2|PIN_A2_OUTPUT_SPEED<<4|PIN_A3_OUTPUT_SPEED<<6|
					   PIN_A4_OUTPUT_SPEED<<8|PIN_A5_OUTPUT_SPEED<<10|PIN_A6_OUTPUT_SPEED<<12|PIN_A7_OUTPUT_SPEED<<14|
					   PIN_A8_OUTPUT_SPEED<<16|PIN_A9_OUTPUT_SPEED<<18|PIN_A10_OUTPUT_SPEED<<20|PIN_A11_OUTPUT_SPEED<<22|
					   PIN_A12_OUTPUT_SPEED<<24|PIN_A13_OUTPUT_SPEED<<26|PIN_A14_OUTPUT_SPEED<<28|PIN_A15_OUTPUT_SPEED<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___OSPEEDR)=PIN_B0_OUTPUT_SPEED|PIN_B1_OUTPUT_SPEED<<2|PIN_B2_OUTPUT_SPEED<<4|PIN_B3_OUTPUT_SPEED<<6|
					   PIN_B4_OUTPUT_SPEED<<8|PIN_B5_OUTPUT_SPEED<<10|PIN_B6_OUTPUT_SPEED<<12|PIN_B7_OUTPUT_SPEED<<14|
					   PIN_B8_OUTPUT_SPEED<<16|PIN_B9_OUTPUT_SPEED<<18|PIN_B10_OUTPUT_SPEED<<20|PIN_B11_OUTPUT_SPEED<<22|
					   PIN_B12_OUTPUT_SPEED<<24|PIN_B13_OUTPUT_SPEED<<26|PIN_B14_OUTPUT_SPEED<<28|PIN_B15_OUTPUT_SPEED<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___OSPEEDR)=PIN_C0_OUTPUT_SPEED|PIN_C1_OUTPUT_SPEED<<2|PIN_C2_OUTPUT_SPEED<<4|PIN_C3_OUTPUT_SPEED<<6|
					   PIN_C4_OUTPUT_SPEED<<8|PIN_C5_OUTPUT_SPEED<<10|PIN_C6_OUTPUT_SPEED<<12|PIN_C7_OUTPUT_SPEED<<14|
					   PIN_C8_OUTPUT_SPEED<<16|PIN_C9_OUTPUT_SPEED<<18|PIN_C10_OUTPUT_SPEED<<20|PIN_C11_OUTPUT_SPEED<<22|
					   PIN_C12_OUTPUT_SPEED<<24|PIN_C13_OUTPUT_SPEED<<26|PIN_C14_OUTPUT_SPEED<<28|PIN_C15_OUTPUT_SPEED<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___OSPEEDR)=PIN_D0_OUTPUT_SPEED|PIN_D1_OUTPUT_SPEED<<2|PIN_D2_OUTPUT_SPEED<<4|PIN_D3_OUTPUT_SPEED<<6|
					   PIN_D4_OUTPUT_SPEED<<8|PIN_D5_OUTPUT_SPEED<<10|PIN_D6_OUTPUT_SPEED<<12|PIN_D7_OUTPUT_SPEED<<14|
					   PIN_D8_OUTPUT_SPEED<<16|PIN_D9_OUTPUT_SPEED<<18|PIN_D10_OUTPUT_SPEED<<20|PIN_D11_OUTPUT_SPEED<<22|
					   PIN_D12_OUTPUT_SPEED<<24|PIN_D13_OUTPUT_SPEED<<26|PIN_D14_OUTPUT_SPEED<<28|PIN_D15_OUTPUT_SPEED<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___OSPEEDR)=PIN_E0_OUTPUT_SPEED|PIN_E1_OUTPUT_SPEED<<2|PIN_E2_OUTPUT_SPEED<<4|PIN_E3_OUTPUT_SPEED<<6|
					   PIN_E4_OUTPUT_SPEED<<8|PIN_E5_OUTPUT_SPEED<<10|PIN_E6_OUTPUT_SPEED<<12|PIN_E7_OUTPUT_SPEED<<14|
					   PIN_E8_OUTPUT_SPEED<<16|PIN_E9_OUTPUT_SPEED<<18|PIN_E10_OUTPUT_SPEED<<20|PIN_E11_OUTPUT_SPEED<<22|
					   PIN_E12_OUTPUT_SPEED<<24|PIN_E13_OUTPUT_SPEED<<26|PIN_E14_OUTPUT_SPEED<<28|PIN_E15_OUTPUT_SPEED<<30;
GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___OSPEEDR)=PIN_H0_OUTPUT_SPEED|PIN_H1_OUTPUT_SPEED<<2|PIN_H2_OUTPUT_SPEED<<4|PIN_H3_OUTPUT_SPEED<<6|
					   PIN_H4_OUTPUT_SPEED<<8|PIN_H5_OUTPUT_SPEED<<10|PIN_H6_OUTPUT_SPEED<<12|PIN_H7_OUTPUT_SPEED<<14|
					   PIN_H8_OUTPUT_SPEED<<16|PIN_H9_OUTPUT_SPEED<<18|PIN_H10_OUTPUT_SPEED<<20|PIN_H11_OUTPUT_SPEED<<22|
					   PIN_H12_OUTPUT_SPEED<<24|PIN_H13_OUTPUT_SPEED<<26|PIN_H14_OUTPUT_SPEED<<28|PIN_H15_OUTPUT_SPEED<<30;

GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___OTYPER)=PIN_A0_OUTPUT_TYPE|PIN_A1_OUTPUT_TYPE<<1|PIN_A2_OUTPUT_TYPE<<2|PIN_A3_OUTPUT_TYPE<<3|
					   PIN_A4_OUTPUT_TYPE<<4|PIN_A5_OUTPUT_TYPE<<5|PIN_A6_OUTPUT_TYPE<<6|PIN_A7_OUTPUT_TYPE<<7|
					   PIN_A8_OUTPUT_TYPE<<8|PIN_A9_OUTPUT_TYPE<<9|PIN_A10_OUTPUT_TYPE<<10|PIN_A11_OUTPUT_TYPE<<11|
					   PIN_A12_OUTPUT_TYPE<<12|PIN_A13_OUTPUT_TYPE<<13|PIN_A14_OUTPUT_TYPE<<14|PIN_A15_OUTPUT_TYPE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___OTYPER)=PIN_B0_OUTPUT_TYPE|PIN_B1_OUTPUT_TYPE<<1|PIN_B2_OUTPUT_TYPE<<2|PIN_B3_OUTPUT_TYPE<<3|
					   PIN_B4_OUTPUT_TYPE<<4|PIN_B5_OUTPUT_TYPE<<5|PIN_B6_OUTPUT_TYPE<<6|PIN_B7_OUTPUT_TYPE<<7|
					   PIN_B8_OUTPUT_TYPE<<8|PIN_B9_OUTPUT_TYPE<<9|PIN_B10_OUTPUT_TYPE<<10|PIN_B11_OUTPUT_TYPE<<11|
					   PIN_B12_OUTPUT_TYPE<<12|PIN_B13_OUTPUT_TYPE<<13|PIN_B14_OUTPUT_TYPE<<14|PIN_B15_OUTPUT_TYPE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___OTYPER)=PIN_C0_OUTPUT_TYPE|PIN_C1_OUTPUT_TYPE<<1|PIN_C2_OUTPUT_TYPE<<2|PIN_C3_OUTPUT_TYPE<<3|
					   PIN_C4_OUTPUT_TYPE<<4|PIN_C5_OUTPUT_TYPE<<5|PIN_C6_OUTPUT_TYPE<<6|PIN_C7_OUTPUT_TYPE<<7|
					   PIN_C8_OUTPUT_TYPE<<8|PIN_C9_OUTPUT_TYPE<<9|PIN_C10_OUTPUT_TYPE<<10|PIN_C11_OUTPUT_TYPE<<11|
					   PIN_C12_OUTPUT_TYPE<<12|PIN_C13_OUTPUT_TYPE<<13|PIN_C14_OUTPUT_TYPE<<14|PIN_C15_OUTPUT_TYPE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___OTYPER)=PIN_D0_OUTPUT_TYPE|PIN_D1_OUTPUT_TYPE<<1|PIN_D2_OUTPUT_TYPE<<2|PIN_D3_OUTPUT_TYPE<<3|
					   PIN_D4_OUTPUT_TYPE<<4|PIN_D5_OUTPUT_TYPE<<5|PIN_D6_OUTPUT_TYPE<<6|PIN_D7_OUTPUT_TYPE<<7|
					   PIN_D8_OUTPUT_TYPE<<8|PIN_D9_OUTPUT_TYPE<<9|PIN_D10_OUTPUT_TYPE<<10|PIN_D11_OUTPUT_TYPE<<11|
					   PIN_D12_OUTPUT_TYPE<<12|PIN_D13_OUTPUT_TYPE<<13|PIN_D14_OUTPUT_TYPE<<14|PIN_D15_OUTPUT_TYPE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___OTYPER)=PIN_E0_OUTPUT_TYPE|PIN_E1_OUTPUT_TYPE<<1|PIN_E2_OUTPUT_TYPE<<2|PIN_E3_OUTPUT_TYPE<<3|
					   PIN_E4_OUTPUT_TYPE<<4|PIN_E5_OUTPUT_TYPE<<5|PIN_E6_OUTPUT_TYPE<<6|PIN_E7_OUTPUT_TYPE<<7|
					   PIN_E8_OUTPUT_TYPE<<8|PIN_E9_OUTPUT_TYPE<<9|PIN_E10_OUTPUT_TYPE<<10|PIN_E11_OUTPUT_TYPE<<11|
					   PIN_E12_OUTPUT_TYPE<<12|PIN_E13_OUTPUT_TYPE<<13|PIN_E14_OUTPUT_TYPE<<14|PIN_E15_OUTPUT_TYPE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___OTYPER)=PIN_H0_OUTPUT_TYPE|PIN_H1_OUTPUT_TYPE<<1|PIN_H2_OUTPUT_TYPE<<2|PIN_H3_OUTPUT_TYPE<<3|
					   PIN_H4_OUTPUT_TYPE<<4|PIN_H5_OUTPUT_TYPE<<5|PIN_H6_OUTPUT_TYPE<<6|PIN_H7_OUTPUT_TYPE<<7|
					   PIN_H8_OUTPUT_TYPE<<8|PIN_H9_OUTPUT_TYPE<<9|PIN_H10_OUTPUT_TYPE<<10|PIN_H11_OUTPUT_TYPE<<11|
					   PIN_H12_OUTPUT_TYPE<<12|PIN_H13_OUTPUT_TYPE<<13|PIN_H14_OUTPUT_TYPE<<14|PIN_H15_OUTPUT_TYPE<<15;

GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___ODR)=PIN_A0_INIT_OUTPUT_STATE|PIN_A1_INIT_OUTPUT_STATE<<1|PIN_A2_INIT_OUTPUT_STATE<<2|PIN_A3_INIT_OUTPUT_STATE<<3|
					   PIN_A4_INIT_OUTPUT_STATE<<4|PIN_A5_INIT_OUTPUT_STATE<<5|PIN_A6_INIT_OUTPUT_STATE<<6|PIN_A7_INIT_OUTPUT_STATE<<7|
					   PIN_A8_INIT_OUTPUT_STATE<<8|PIN_A9_INIT_OUTPUT_STATE<<9|PIN_A10_INIT_OUTPUT_STATE<<10|PIN_A11_INIT_OUTPUT_STATE<<11|
					   PIN_A12_INIT_OUTPUT_STATE<<12|PIN_A13_INIT_OUTPUT_STATE<<13|PIN_A14_INIT_OUTPUT_STATE<<14|PIN_A15_INIT_OUTPUT_STATE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___ODR)=PIN_B0_INIT_OUTPUT_STATE|PIN_B1_INIT_OUTPUT_STATE<<1|PIN_B2_INIT_OUTPUT_STATE<<2|PIN_B3_INIT_OUTPUT_STATE<<3|
					   PIN_B4_INIT_OUTPUT_STATE<<4|PIN_B5_INIT_OUTPUT_STATE<<5|PIN_B6_INIT_OUTPUT_STATE<<6|PIN_B7_INIT_OUTPUT_STATE<<7|
					   PIN_B8_INIT_OUTPUT_STATE<<8|PIN_B9_INIT_OUTPUT_STATE<<9|PIN_B10_INIT_OUTPUT_STATE<<10|PIN_B11_INIT_OUTPUT_STATE<<11|
					   PIN_B12_INIT_OUTPUT_STATE<<12|PIN_B13_INIT_OUTPUT_STATE<<13|PIN_B14_INIT_OUTPUT_STATE<<14|PIN_B15_INIT_OUTPUT_STATE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___ODR)=PIN_C0_INIT_OUTPUT_STATE|PIN_C1_INIT_OUTPUT_STATE<<1|PIN_C2_INIT_OUTPUT_STATE<<2|PIN_C3_INIT_OUTPUT_STATE<<3|
					   PIN_C4_INIT_OUTPUT_STATE<<4|PIN_C5_INIT_OUTPUT_STATE<<5|PIN_C6_INIT_OUTPUT_STATE<<6|PIN_C7_INIT_OUTPUT_STATE<<7|
					   PIN_C8_INIT_OUTPUT_STATE<<8|PIN_C9_INIT_OUTPUT_STATE<<9|PIN_C10_INIT_OUTPUT_STATE<<10|PIN_C11_INIT_OUTPUT_STATE<<11|
					   PIN_C12_INIT_OUTPUT_STATE<<12|PIN_C13_INIT_OUTPUT_STATE<<13|PIN_C14_INIT_OUTPUT_STATE<<14|PIN_C15_INIT_OUTPUT_STATE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___ODR)=PIN_D0_INIT_OUTPUT_STATE|PIN_D1_INIT_OUTPUT_STATE<<1|PIN_D2_INIT_OUTPUT_STATE<<2|PIN_D3_INIT_OUTPUT_STATE<<3|
					   PIN_D4_INIT_OUTPUT_STATE<<4|PIN_D5_INIT_OUTPUT_STATE<<5|PIN_D6_INIT_OUTPUT_STATE<<6|PIN_D7_INIT_OUTPUT_STATE<<7|
					   PIN_D8_INIT_OUTPUT_STATE<<8|PIN_D9_INIT_OUTPUT_STATE<<9|PIN_D10_INIT_OUTPUT_STATE<<10|PIN_D11_INIT_OUTPUT_STATE<<11|
					   PIN_D12_INIT_OUTPUT_STATE<<12|PIN_D13_INIT_OUTPUT_STATE<<13|PIN_D14_INIT_OUTPUT_STATE<<14|PIN_D15_INIT_OUTPUT_STATE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___ODR)=PIN_E0_INIT_OUTPUT_STATE|PIN_E1_INIT_OUTPUT_STATE<<1|PIN_E2_INIT_OUTPUT_STATE<<2|PIN_E3_INIT_OUTPUT_STATE<<3|
					   PIN_E4_INIT_OUTPUT_STATE<<4|PIN_E5_INIT_OUTPUT_STATE<<5|PIN_E6_INIT_OUTPUT_STATE<<6|PIN_E7_INIT_OUTPUT_STATE<<7|
					   PIN_E8_INIT_OUTPUT_STATE<<8|PIN_E9_INIT_OUTPUT_STATE<<9|PIN_E10_INIT_OUTPUT_STATE<<10|PIN_E11_INIT_OUTPUT_STATE<<11|
					   PIN_E12_INIT_OUTPUT_STATE<<12|PIN_E13_INIT_OUTPUT_STATE<<13|PIN_E14_INIT_OUTPUT_STATE<<14|PIN_E15_INIT_OUTPUT_STATE<<15;
GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___ODR)=PIN_H0_INIT_OUTPUT_STATE|PIN_H1_INIT_OUTPUT_STATE<<1|PIN_H2_INIT_OUTPUT_STATE<<2|PIN_H3_INIT_OUTPUT_STATE<<3|
					   PIN_H4_INIT_OUTPUT_STATE<<4|PIN_H5_INIT_OUTPUT_STATE<<5|PIN_H6_INIT_OUTPUT_STATE<<6|PIN_H7_INIT_OUTPUT_STATE<<7|
					   PIN_H8_INIT_OUTPUT_STATE<<8|PIN_H9_INIT_OUTPUT_STATE<<9|PIN_H10_INIT_OUTPUT_STATE<<10|PIN_H11_INIT_OUTPUT_STATE<<11|
					   PIN_H12_INIT_OUTPUT_STATE<<12|PIN_H13_INIT_OUTPUT_STATE<<13|PIN_H14_INIT_OUTPUT_STATE<<14|PIN_H15_INIT_OUTPUT_STATE<<15;

GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___AFRL)=PIN_A0_ALTERNATE_FUNCTION|PIN_A1_ALTERNATE_FUNCTION<<4|PIN_A2_ALTERNATE_FUNCTION<<8|PIN_A3_ALTERNATE_FUNCTION<<12|
					   PIN_A4_ALTERNATE_FUNCTION<<16|PIN_A5_ALTERNATE_FUNCTION<<20|PIN_A6_ALTERNATE_FUNCTION<<24|PIN_A7_ALTERNATE_FUNCTION<<28;

GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___AFRH)=PIN_A8_ALTERNATE_FUNCTION|PIN_A9_ALTERNATE_FUNCTION<<4|PIN_A10_ALTERNATE_FUNCTION<<8|PIN_A11_ALTERNATE_FUNCTION<<12|
					   PIN_A12_ALTERNATE_FUNCTION<<16|PIN_A13_ALTERNATE_FUNCTION<<20|PIN_A14_ALTERNATE_FUNCTION<<24|PIN_A15_ALTERNATE_FUNCTION<<28;

GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___AFRL)=PIN_H0_ALTERNATE_FUNCTION|PIN_H1_ALTERNATE_FUNCTION<<4|PIN_H2_ALTERNATE_FUNCTION<<8|PIN_H3_ALTERNATE_FUNCTION<<12|
					   PIN_H4_ALTERNATE_FUNCTION<<16|PIN_H5_ALTERNATE_FUNCTION<<20|PIN_H6_ALTERNATE_FUNCTION<<24|PIN_H7_ALTERNATE_FUNCTION<<28;

GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___AFRH)=PIN_H8_ALTERNATE_FUNCTION|PIN_H9_ALTERNATE_FUNCTION<<1|PIN_H10_ALTERNATE_FUNCTION<<2|PIN_H11_ALTERNATE_FUNCTION<<11|
					   PIN_H12_ALTERNATE_FUNCTION<<12|PIN_H13_ALTERNATE_FUNCTION<<13|PIN_H14_ALTERNATE_FUNCTION<<14|PIN_H15_ALTERNATE_FUNCTION<<15;

GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___AFRL)=PIN_C0_ALTERNATE_FUNCTION|PIN_C1_ALTERNATE_FUNCTION<<4|PIN_C2_ALTERNATE_FUNCTION<<8|PIN_C3_ALTERNATE_FUNCTION<<12|
					   PIN_C4_ALTERNATE_FUNCTION<<16|PIN_C5_ALTERNATE_FUNCTION<<20|PIN_C6_ALTERNATE_FUNCTION<<24|PIN_C7_ALTERNATE_FUNCTION<<28;

GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___AFRH)=PIN_C8_ALTERNATE_FUNCTION|PIN_C9_ALTERNATE_FUNCTION<<1|PIN_C10_ALTERNATE_FUNCTION<<2|PIN_C11_ALTERNATE_FUNCTION<<11|
					   PIN_C12_ALTERNATE_FUNCTION<<12|PIN_C13_ALTERNATE_FUNCTION<<13|PIN_C14_ALTERNATE_FUNCTION<<14|PIN_C15_ALTERNATE_FUNCTION<<15;

GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___AFRL)=PIN_D0_ALTERNATE_FUNCTION|PIN_D1_ALTERNATE_FUNCTION<<4|PIN_D2_ALTERNATE_FUNCTION<<8|PIN_D3_ALTERNATE_FUNCTION<<12|
					   PIN_D4_ALTERNATE_FUNCTION<<16|PIN_D5_ALTERNATE_FUNCTION<<20|PIN_D6_ALTERNATE_FUNCTION<<24|PIN_D7_ALTERNATE_FUNCTION<<28;

GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___AFRH)=PIN_D8_ALTERNATE_FUNCTION|PIN_D9_ALTERNATE_FUNCTION<<1|PIN_D10_ALTERNATE_FUNCTION<<2|PIN_D11_ALTERNATE_FUNCTION<<11|
					   PIN_D12_ALTERNATE_FUNCTION<<12|PIN_D13_ALTERNATE_FUNCTION<<13|PIN_D14_ALTERNATE_FUNCTION<<14|PIN_D15_ALTERNATE_FUNCTION<<15;

GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___AFRL)=PIN_E0_ALTERNATE_FUNCTION|PIN_E1_ALTERNATE_FUNCTION<<4|PIN_E2_ALTERNATE_FUNCTION<<8|PIN_E3_ALTERNATE_FUNCTION<<12|
					   PIN_E4_ALTERNATE_FUNCTION<<16|PIN_E5_ALTERNATE_FUNCTION<<20|PIN_E6_ALTERNATE_FUNCTION<<24|PIN_E7_ALTERNATE_FUNCTION<<28;

GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___AFRH)=PIN_E8_ALTERNATE_FUNCTION|PIN_E9_ALTERNATE_FUNCTION<<1|PIN_E10_ALTERNATE_FUNCTION<<2|PIN_E11_ALTERNATE_FUNCTION<<11|
					   PIN_E12_ALTERNATE_FUNCTION<<12|PIN_E13_ALTERNATE_FUNCTION<<13|PIN_E14_ALTERNATE_FUNCTION<<14|PIN_E15_ALTERNATE_FUNCTION<<15;

GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___AFRL)=PIN_H0_ALTERNATE_FUNCTION|PIN_H1_ALTERNATE_FUNCTION<<4|PIN_H2_ALTERNATE_FUNCTION<<8|PIN_H3_ALTERNATE_FUNCTION<<12|
					   PIN_H4_ALTERNATE_FUNCTION<<16|PIN_H5_ALTERNATE_FUNCTION<<20|PIN_H6_ALTERNATE_FUNCTION<<24|PIN_H7_ALTERNATE_FUNCTION<<28;

GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___AFRH)=PIN_H8_ALTERNATE_FUNCTION|PIN_H9_ALTERNATE_FUNCTION<<1|PIN_H10_ALTERNATE_FUNCTION<<2|PIN_H11_ALTERNATE_FUNCTION<<11|
					   PIN_H12_ALTERNATE_FUNCTION<<12|PIN_H13_ALTERNATE_FUNCTION<<13|PIN_H14_ALTERNATE_FUNCTION<<14|PIN_H15_ALTERNATE_FUNCTION<<15;

GPIO_REG_BAND_ALIAS(GPIO__PORT___A,GPIO__REG___LCKR)=PIN_A0_LOCK_STATE|PIN_A1_LOCK_STATE<<1|PIN_A2_LOCK_STATE<<2|PIN_A3_LOCK_STATE<<3|
					   PIN_A4_LOCK_STATE<<4|PIN_A5_LOCK_STATE<<5|PIN_A6_LOCK_STATE<<6|PIN_A7_LOCK_STATE<<7|
					   PIN_A8_LOCK_STATE<<8|PIN_A9_LOCK_STATE<<9|PIN_A10_LOCK_STATE<<10|PIN_A11_LOCK_STATE<<11|
					   PIN_A12_LOCK_STATE<<12|PIN_A13_LOCK_STATE<<13|PIN_A14_LOCK_STATE<<14|PIN_A15_LOCK_STATE<<15|PORT_A_MAIN_LOCK_STATE<<16;
GPIO_REG_BAND_ALIAS(GPIO__PORT___B,GPIO__REG___LCKR)=PIN_H0_LOCK_STATE|PIN_H1_LOCK_STATE<<1|PIN_H2_LOCK_STATE<<2|PIN_H3_LOCK_STATE<<3|
					   PIN_H4_LOCK_STATE<<4|PIN_H5_LOCK_STATE<<5|PIN_H6_LOCK_STATE<<6|PIN_H7_LOCK_STATE<<7|
					   PIN_H8_LOCK_STATE<<8|PIN_H9_LOCK_STATE<<9|PIN_H10_LOCK_STATE<<10|PIN_H11_LOCK_STATE<<11|
					   PIN_H12_LOCK_STATE<<12|PIN_H13_LOCK_STATE<<13|PIN_H14_LOCK_STATE<<14|PIN_H15_LOCK_STATE<<15|PORT_B_MAIN_LOCK_STATE<<16;
GPIO_REG_BAND_ALIAS(GPIO__PORT___C,GPIO__REG___LCKR)=PIN_C0_LOCK_STATE|PIN_C1_LOCK_STATE<<1|PIN_C2_LOCK_STATE<<2|PIN_C3_LOCK_STATE<<3|
					   PIN_C4_LOCK_STATE<<4|PIN_C5_LOCK_STATE<<5|PIN_C6_LOCK_STATE<<6|PIN_C7_LOCK_STATE<<7|
					   PIN_C8_LOCK_STATE<<8|PIN_C9_LOCK_STATE<<9|PIN_C10_LOCK_STATE<<10|PIN_C11_LOCK_STATE<<11|
					   PIN_C12_LOCK_STATE<<12|PIN_C13_LOCK_STATE<<13|PIN_C14_LOCK_STATE<<14|PIN_C15_LOCK_STATE<<15|PORT_C_MAIN_LOCK_STATE<<16;
GPIO_REG_BAND_ALIAS(GPIO__PORT___D,GPIO__REG___LCKR)=PIN_D0_LOCK_STATE|PIN_D1_LOCK_STATE<<1|PIN_D2_LOCK_STATE<<2|PIN_D3_LOCK_STATE<<3|
					   PIN_D4_LOCK_STATE<<4|PIN_D5_LOCK_STATE<<5|PIN_D6_LOCK_STATE<<6|PIN_D7_LOCK_STATE<<7|
					   PIN_D8_LOCK_STATE<<8|PIN_D9_LOCK_STATE<<9|PIN_D10_LOCK_STATE<<10|PIN_D11_LOCK_STATE<<11|
					   PIN_D12_LOCK_STATE<<12|PIN_D13_LOCK_STATE<<13|PIN_D14_LOCK_STATE<<14|PIN_D15_LOCK_STATE<<15|PORT_D_MAIN_LOCK_STATE<<16;
GPIO_REG_BAND_ALIAS(GPIO__PORT___E,GPIO__REG___LCKR)=PIN_E0_LOCK_STATE|PIN_E1_LOCK_STATE<<1|PIN_E2_LOCK_STATE<<2|PIN_E3_LOCK_STATE<<3|
					   PIN_E4_LOCK_STATE<<4|PIN_E5_LOCK_STATE<<5|PIN_E6_LOCK_STATE<<6|PIN_E7_LOCK_STATE<<7|
					   PIN_E8_LOCK_STATE<<8|PIN_E9_LOCK_STATE<<9|PIN_E10_LOCK_STATE<<10|PIN_E11_LOCK_STATE<<11|
					   PIN_E12_LOCK_STATE<<12|PIN_E13_LOCK_STATE<<13|PIN_E14_LOCK_STATE<<14|PIN_E15_LOCK_STATE<<15|PORT_E_MAIN_LOCK_STATE<<16;
GPIO_REG_BAND_ALIAS(GPIO__PORT___H,GPIO__REG___LCKR)=PIN_H0_LOCK_STATE|PIN_H1_LOCK_STATE<<1|PIN_H2_LOCK_STATE<<2|PIN_H3_LOCK_STATE<<3|
					   PIN_H4_LOCK_STATE<<4|PIN_H5_LOCK_STATE<<5|PIN_H6_LOCK_STATE<<6|PIN_H7_LOCK_STATE<<7|
					   PIN_H8_LOCK_STATE<<8|PIN_H9_LOCK_STATE<<9|PIN_H10_LOCK_STATE<<10|PIN_H11_LOCK_STATE<<11|
					   PIN_H12_LOCK_STATE<<12|PIN_H13_LOCK_STATE<<13|PIN_H14_LOCK_STATE<<14|PIN_H15_LOCK_STATE<<15|PORT_H_MAIN_LOCK_STATE<<16;




}


/*RUN-TIME CONFIGURATION*/


void GPIO_ct::GPIO_vSetMode(Pin_et Pin_e,Mode_et Mode_e)
{

		  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___MODER,(Pin_e%16)*2)=Mode_e&1;
		  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___MODER,((Pin_e%16)*2)+1)=Mode_e>>1;
}


ErrorStatus_et GPIO_ct::GPIO_enuSetMode(Pin_et aPin_e[],Mode_et aMode_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___MODER,(aPin_e[u8IndexLoc]%16)*2)=aMode_e[u8IndexLoc]&1;
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___MODER,((aPin_e[u8IndexLoc]%16)*2)+1)=aMode_e[u8IndexLoc]>>1;
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;

}




void GPIO_ct::GPIO_vSetAttachmentType(Pin_et Pin_e,AttachmentType_et AttachmentType_e)
{
			  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___PUPDR,(Pin_e%16)*2)=AttachmentType_e&1;
			  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___PUPDR,((Pin_e%16)*2)+1)=AttachmentType_e>>1;
}


ErrorStatus_et GPIO_ct::GPIO_enuSetAttachmentType(Pin_et aPin_e[],AttachmentType_et aAttachmentType_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___PUPDR,(aPin_e[u8IndexLoc]%16)*2)=aAttachmentType_e[u8IndexLoc]&1;
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___PUPDR,((aPin_e[u8IndexLoc]%16)*2)+1)=aAttachmentType_e[u8IndexLoc]>>1;
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;

}



void GPIO_ct::GPIO_vSetOutPutType(Pin_et Pin_e,OutPutType_et OutPutType_e)
{
			  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___OTYPER,Pin_e%16)=OutPutType_e;
}


ErrorStatus_et GPIO_ct::GPIO_enuSetOutPutType(Pin_et aPin_e[],OutPutType_et aOutPutType_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___OTYPER,aPin_e[u8IndexLoc]%16)=aOutPutType_e[u8IndexLoc];
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;

}





void GPIO_ct::GPIO_vSetOutPutSpeed(Pin_et Pin_e,OutPutSpeed_et OutPutSpeed_e)
{
			  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___OSPEEDR,(Pin_e%16)*2)=OutPutSpeed_e&1;
			  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___OSPEEDR,((Pin_e%16)*2)+1)=OutPutSpeed_e>>1;
}


ErrorStatus_et GPIO_ct::GPIO_enuSetOutPutSpeed(Pin_et aPin_e[],OutPutSpeed_et aOutPutSpeed_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				  GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___OSPEEDR,(aPin_e[u8IndexLoc]%16)*2)=aOutPutSpeed_e[u8IndexLoc]&1;
				  GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___OSPEEDR,((aPin_e[u8IndexLoc]%16)*2)+1)=aOutPutSpeed_e[u8IndexLoc]>>1;
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;


}




/*RUN-TIME APIs*/
void GPIO_ct::GPIO_vWrite(Pin_et Pin_e,LevelState_et LevelState_e)
{
		  GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___ODR,Pin_e%16)=LevelState_e;
}

void GPIO_ct::GPIO_vWrite(Port_et Port_e,uint16_kt u16PortStateCpy)
{
		  GPIO_REG_BAND_ALIAS(Port_e,GPIO__REG___ODR)=u16PortStateCpy;
}
ErrorStatus_et GPIO_ct::GPIO_enuWrite(Pin_et aPin_e[],LevelState_et aLevelState_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___ODR,aPin_e[u8IndexLoc]%16)=aLevelState_e[u8IndexLoc];
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;



}
ErrorStatus_et GPIO_ct::GPIO_enuWrite(Pin_et aPin_e[],uint64_kt u64StreamLevelsCpy,uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<64)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___ODR,aPin_e[u8IndexLoc]%16)=u64StreamLevelsCpy&1;
				u64StreamLevelsCpy>>=1;
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;



}

void GPIO_ct::GPIO_vToggle(Pin_et Pin_e)
{
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___ODR,Pin_e%16)^=1;
}
void GPIO_ct::GPIO_vToggle(Port_et Port_e)
{
	GPIO_REG_BAND_ALIAS(Port_e,GPIO__REG___ODR)^=0X0000FFFF;
}
ErrorStatus_et GPIO_ct::GPIO_enuToggle(Pin_et aPin_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___ODR,aPin_e[u8IndexLoc]%16)^=1;
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;

}


LevelState_et  GPIO_ct::GPIO_enuRead(Pin_et Pin_e)
{
	return (LevelState_et)GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___IDR,Pin_e%16);
}


uint16_kt GPIO_ct::GPIO_u16Read(Port_et Port_e)
{

	  return (uint16_kt)GPIO_REG_BAND_ALIAS(Port_e,GPIO__REG___IDR);

}


ErrorStatus_et GPIO_ct::GPIO_enuRead(Pin_et aPin_e[],LevelState_et aLevelState_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				aLevelState_e[u8IndexLoc]=(LevelState_et)GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___IDR,aPin_e[u8IndexLoc]%16);
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;



}
ErrorStatus_et GPIO_ct::GPIO_enuRead(Pin_et aPin_e[],uint64_kt * pu64StreamLevels,uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<64)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(u8IndexLoc=u8LengthCpy-1;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				*pu64StreamLevels|=GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___IDR,aPin_e[u8IndexLoc]%16);
				(*pu64StreamLevels)<<=1;
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;



}
void GPIO_ct::GPIO_vSetLock(Pin_et Pin_e,State_et State_e)
{
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___LCKR,Pin_e%16)=State_e;
}
void GPIO_ct::GPIO_vSetLock(Port_et Port_e,uint16_kt u16PortStateCpy)
{
	GPIO_REG_BAND_ALIAS(Port_e,GPIO__REG___LCKR)=u16PortStateCpy;
}
ErrorStatus_et GPIO_ct::GPIO_enuSetLock(Pin_et aPin_e[],State_et aState_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___LCKR,aPin_e[u8IndexLoc]%16)=aState_e[u8IndexLoc];
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;


}
void GPIO_ct::GPIO_vSetMainLock(Port_et Port_e,State_et State_e)
{
	GPIO_BIT_BAND_ALIAS(Port_e,GPIO__REG___LCKR,16)=State_e;
}

void GPIO_ct::GPIO_vSetAlternateFunction(Pin_et Pin_e,AlternateFunction_et AlternateFunction_e)
{
	if(Pin_e%16<8)
	{
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRL,(Pin_e%16)*4)=AlternateFunction_e&1;
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRL,((Pin_e%16)*4)+1)=(AlternateFunction_e>>1)&1;
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRL,((Pin_e%16)*4)+2)=(AlternateFunction_e>>2)&1;
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRL,((Pin_e%16)*4)+3)=(AlternateFunction_e>>3)&1;
	}
	else
	{
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRH,(Pin_e%16)*4)=AlternateFunction_e&1;
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRH,((Pin_e%16)*4)+1)=(AlternateFunction_e>>1)&1;
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRH,((Pin_e%16)*4)+2)=(AlternateFunction_e>>2)&1;
	GPIO_BIT_BAND_ALIAS(Pin_e/16,GPIO__REG___AFRH,((Pin_e%16)*4)+3)=(AlternateFunction_e>>3)&1;
	}
}
ErrorStatus_et GPIO_ct::GPIO_enuSetAlternateFunction(Pin_et aPin_e[],AlternateFunction_et aAlternateFunction_e[],uint8_kt u8LengthCpy)
{
	uint8_kt u8IndexLoc=0;
	ErrorStatus_et ErrorStatusLoc_e=EOK;
	if(u8LengthCpy<96)
	{
		if(DetectMultipleOccurance((uint8_kt *)aPin_e,u8LengthCpy)==EOK)
		{
			for(;u8IndexLoc<u8LengthCpy;u8IndexLoc++)
			{
				if(aPin_e[u8IndexLoc]%16<8)
				{
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRL,(aPin_e[u8IndexLoc]%16)*4)=aAlternateFunction_e[u8IndexLoc]&1;
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRL,((aPin_e[u8IndexLoc]%16)*4)+1)=(aAlternateFunction_e[u8IndexLoc]>>1)&1;
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRL,((aPin_e[u8IndexLoc]%16)*4)+2)=(aAlternateFunction_e[u8IndexLoc]>>2)&1;
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRL,((aPin_e[u8IndexLoc]%16)*4)+3)=(aAlternateFunction_e[u8IndexLoc]>>3)&1;
				}
				else
				{
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRH,(aPin_e[u8IndexLoc]%16)*4)=aAlternateFunction_e[u8IndexLoc]&1;
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRH,((aPin_e[u8IndexLoc]%16)*4)+1)=(aAlternateFunction_e[u8IndexLoc]>>1)&1;
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRH,((aPin_e[u8IndexLoc]%16)*4)+2)=(aAlternateFunction_e[u8IndexLoc]>>2)&1;
					GPIO_BIT_BAND_ALIAS(aPin_e[u8IndexLoc]/16,GPIO__REG___AFRH,((aPin_e[u8IndexLoc]%16)*4)+3)=(aAlternateFunction_e[u8IndexLoc]>>3)&1;
				}
			}
		}
		else
		{
			ErrorStatusLoc_e=MULTI_OCCUR;
		}

	}
	else
	{
		ErrorStatusLoc_e=PARAM_OUT_OF_RANGE;
	}
	return ErrorStatusLoc_e;

}

