/**************************************/
/* Description : MPU interface File   */
/* Author      : hossam               */
/* Version     : 0.1V                 */
/* Date        : 22:06:41  23 Jul 2023*/
/* History     : 0.1V Initial Creation*/
/**************************************/




#ifndef MPU_INTERFACE_H
#define MPU_INTERFACE_H
typedef enum  __attribute__((__packed__)){
	 MPU__MEMORY_CONNECTION___UNIFIED,
	 MPU__MEMORY_CONNECTION___SEPERATE,
}MemoryConnection_et;
typedef enum  __attribute__((__packed__)){
	 MPU__STATE___DISABLE,
	 MPU__STATE___ENABLE,
}MPU_State_et;

typedef enum  __attribute__((__packed__)){
	 MPU__ACCESS_PERMISSION___STRONGLY_ORDERED__SHAREABLE,
	 MPU__ACCESS_PERMISSION___DEVICE__SHAREABLE,
	 MPU__ACCESS_PERMISSION___DEVICE__NOT_SHAREABLE=0b00010000,


	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_AND_INNER_NONCACHEABLE=0b0100000,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_NONCACHEABLE_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0100001,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_NONCACHEABLE_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0100010,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_NONCACHEABLE_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0100011,

	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_BACK__WRITE_AND_READ_ALLOCATE_AND_INNER_NONCACHEABLE=0b0101000,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0101001,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_BACK__WRITE_AND_READ_ALLOCATE_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0101010,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_BACK__WRITE_AND_READ_ALLOCATE_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0101011,

	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_THROUGH__NO_WRITE_ALLOCATE_AND_INNER_NONCACHEABLE=0b0110000,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_THROUGH__NO_WRITE_ALLOCATE_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0110001,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0110010,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_THROUGH__NO_WRITE_ALLOCATE_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0110011,

	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_BACK__NO_WRITE_ALLOCATE_AND_INNER_NONCACHEABLE=0b0111000,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_BACK__NO_WRITE_ALLOCATE_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0111001,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_WRITE_BACK__NO_WRITE_ALLOCATE_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0111010,
	 MPU__ACCESS_PERMISSION___NORMAL__NOT_SHAREABLE__OUTER_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0111011,





	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_AND_INNER_NONCACHEABLE=0b0100100,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_NONCACHEABLE_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0100101,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_NONCACHEABLE_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0100110,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_NONCACHEABLE_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0100111,

	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_BACK__WRITE_AND_READ_ALLOCATE_AND_INNER_NONCACHEABLE=0b0101100,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0101101,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_BACK__WRITE_AND_READ_ALLOCATE_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0101110,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_BACK__WRITE_AND_READ_ALLOCATE_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0101111,

	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_THROUGH__NO_WRITE_ALLOCATE_AND_INNER_NONCACHEABLE=0b0110100,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_THROUGH__NO_WRITE_ALLOCATE_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0110101,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0110110,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_THROUGH__NO_WRITE_ALLOCATE_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0110111,

	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_BACK__NO_WRITE_ALLOCATE_AND_INNER_NONCACHEABLE=0b0111100,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_BACK__NO_WRITE_ALLOCATE_AND_INNER_WRITE_BACK__WRITE_AND_READ_ALLOCATE=0b0111101,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_WRITE_BACK__NO_WRITE_ALLOCATE_AND_INNER_WRITE_THROUGH__NO_WRITE_ALLOCATE=0b0111110,
	 MPU__ACCESS_PERMISSION___NORMAL__SHAREABLE__OUTER_AND_INNER_WRITE_BACK__NO_WRITE_ALLOCATE=0b0111111,

}MemoryConfig_et;
typedef enum  __attribute__((__packed__)){
	 MPU__REGION___0,
	 MPU__REGION___1,
	 MPU__REGION___2,
	 MPU__REGION___3,
	 MPU__REGION___4,
	 MPU__REGION___5,
	 MPU__REGION___6,
	 MPU__REGION___7
}Region_et;
typedef enum  __attribute__((__packed__)){
	 MPU__REGION_SIZE___32B=4,
	 MPU__REGION_SIZE___64B,
	 MPU__REGION_SIZE___128B,
	 MPU__REGION_SIZE___256B,
	 MPU__REGION_SIZE___512B,
	 MPU__REGION_SIZE___1KB,
	 MPU__REGION_SIZE___2KB,
	 MPU__REGION_SIZE___4KB,
	 MPU__REGION_SIZE___8KB,
	 MPU__REGION_SIZE___16KB,
	 MPU__REGION_SIZE___32KB,
	 MPU__REGION_SIZE___64KB,
	 MPU__REGION_SIZE___128KB,
	 MPU__REGION_SIZE___256KB,
	 MPU__REGION_SIZE___512KB,
	 MPU__REGION_SIZE___1MB,
	 MPU__REGION_SIZE___2MB,
	 MPU__REGION_SIZE___4MB,
	 MPU__REGION_SIZE___8MB,
	 MPU__REGION_SIZE___16MB,
	 MPU__REGION_SIZE___32MB,
	 MPU__REGION_SIZE___64MB,
	 MPU__REGION_SIZE___128MB,
	 MPU__REGION_SIZE___256MB,
	 MPU__REGION_SIZE___512MB,
	 MPU__REGION_SIZE___1GB,
	 MPU__REGION_SIZE___2GB,
	 MPU__REGION_SIZE___4GB
}RegionSize_et;
typedef enum __attribute__((__packed__)){
	MPU__ACCESS_PERMISSION___NO_ACCESS_IN_ANY_MODE,
	MPU__ACCESS_PERMISSION___READ_AND_WRITE_IN_PRIVILEGED_MODE_AND_NO_ACCESS_IN_UNPRIVILEGED_MODE,
	MPU__ACCESS_PERMISSION___READ_AND_WRITE_IN_PRIVILEGED_MODE_AND_READ_ONLY_IN_UNPRIVILEGED_MODE,
	MPU__ACCESS_PERMISSION___FULL_ACCESS_IN_ANY_MODE,
	MPU__ACCESS_PERMISSION___READ_ONLY_IN_PRIVILEGED_MODE_AND_NO_ACCESS_IN_UNPRIVILEGED_MODE=5,
	MPU__ACCESS_PERMISSION___READ_ONLY_IN_ANY_MODE
}AccessPermission_et;
class MPU_ct{
public:
MPU_ct(void);
ErrorStatus_et MPU_enuReadSupportRegions(MemoryConnection_et * pMemoryConnection_e,
										 uint8_kt *pu8NumberOfDataRegions,
										 uint8_kt *pu8NumberOfInstructionRegions);
void MPU_vEnable(void);
void MPU_vDisable(void);
void MPU_vDefaultMeomryMapBackGroundRegionEnable(void);
void MPU_vDefaultMeomryMapBackGroundRegionDisable(void);
void MPU_vUseMPU_InHandlerModeEnable(void);
void MPU_vUseMPU_InHandlerModeDisable(void);
ErrorStatus_et  MPU_enuSetRegionConfig(uint32_kt u32BaseAddressCpy,
											   Region_et Region_e,
											   RegionSize_et RegionSize_e,
											   MPU_State_et SubRegionState_e,
											   MemoryConfig_et MemoryConfig_e,
											   AccessPermission_et AccessPermission_e,
											   MPU_State_et InstructionFetchesState_e);

};






#endif
